# Generated by Django 2.2.4 on 2021-03-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examApp', '0002_auto_20210302_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='description',
        ),
    ]
